#!/bin/bash

printf "
####################
# System installer #
####################\n\n"

if [ $UID -ne 0 ]; then
	printf "Script must be run with root privelages\n\n"
	exit 1
fi

echo 'Enter Username: '
read username
echo 'Enter password: '
read -s password
echo ; read -p 'Perform auto grub install? ' -n 1 -r grubconfirm
if [[ $grubconfirm =~ ^[Yy]$ ]]; then
echo ; read -p 'Setup device as removable? ' -n 1 -r removable
else
removable="n"
fi
printf "\n\n\n"

dir=$(pwd)
scriptdir=$(dirname $0)

pacstrap $dir base linux linux-firmware
echo 'KEYMAP=i386/qwerty/uk' >> $dir/etc/vconsole.conf
ln -sf $dir/usr/share/zoneinfo/Europe/London $dir/etc/localtime
genfstab -U $dir >> $dir/etc/fstab
echo 'oDesktop-i3' >> $dir/etc/hostname
sed -i -e's/#en_US.UTF-8/en_US.UTF-8/g' $dir/etc/locale.gen
sed -i -e's/#en_GB.UTF-8/en_GB.UTF-8/g' $dir/etc/locale.gen
cp -r "$(dirname $scriptdir)" "$dir"

printf "\n\nChrooting into target device...\n\n"
arch-chroot $dir /bin/bash <<EOT
bash -c "/linextras/archi3/scripts/installhelper $username $password $grubconfirm $removable"
EOT