#!/bin/bash

scriptdir=$(dirname $0)
source $scriptdir/pkgs

sudo pacman -Sy

sudo pacman -S --needed $pkgs
sudo systemctl enable $services
sudo systemctl enable --user $servicesuser

mkdir -p $HOME/Dev/AUR
cd $HOME/Dev/AUR
for aurpkg in $pkgsyay ; do 
	git clone http://aur.archlinux.org/$aurpkg
	cd $aurpkg
	git pull
	makepkg -sic --skipinteg --noconfirm --needed
	cd ..
done
