#!/bin/bash

scriptdir=$(dirname $0)
source $scriptdir/pkgs

locale-gen

echo 'Enter root passwd'
passwd root
echo 'Enter Username'
read username
echo 'Enter $username passwd'
useradd -m -G wheel $username
passwd $username

pacman -Sy --noconfirm --needed $pkgs &&
systemctl enable $services


sudo -u $username -H sh -c "
cp -rf $scriptdir/dotfiles/.[^.]* /home/$username
cp -f $scriptdir/dotfiles/.bashrc $HOME
cp -rf $scriptdir/scripts/amount /usr/bin

if [ $username = 'oran' ]; then
	git config --global user.email "oran.mcnair@gmail.com"
	git config --global user.name "Oran Ellis"
	git config --global credential.helper store
fi

mkdir -p $HOME/Dev $HOME/Downloads $HOME/Pictures/Backgrounds
cp $(dirname $scriptdir)/assets/bg.jpg $HOME/Pictures/Backgrounds

cd $HOME/Dev
for aurpkg in $pkgsyay do 
git clone http://aur.archlinux.org/$aurpkg
cd $aurpkg
makepkg -sic --skipinteg --noconfirm
cd ..
rm -rf $aurpkg
done
"

read -p "Perform auto grub install? " -n 1 -r grubconfirm
echo 
if [[ $grubconfirm =~ ^[Yy]$ ]]; then
	sed -e "s/[p]\?[1-9]$//"
	echo $(findmnt --output source --noheadings -T . ) | sed "s/[p]\?[1-9]$//" | lsblk -o PATH,PARTTYPENAME | sed -n 's/[ ]*EFI System//p'
	efidevice=echo $(findmnt --output source --noheadings -T . ) | sed "s/[p]\?[1-9]$//" | lsblk -o PATH,PARTTYPENAME | sed -n 's/[ ]*EFI System//p'
	mkdir -p /boot/efi
	mount $efidevice /boot/efi
	
	read -p "Setup device as removable? " -n 1 -r grubconfirm
	echo
	if [[ $grubconfirm =~ ^[Yy]$ ]]; then
		grub-install --bootloader --boot-directory=/boot --efi-directory=/boot/efi --themes=starlight
	else	
		grub-install --bootloader-id="Archi3" --boot-directory=/boot --efi-directory=/boot/efi --themes=starlight
	fi

	sed -i'' -e'/GRUB_TIMEOUT=.*/d' -e'/GRUB_DISTRIBUTOR=.*/d' -e'/GRUB_CMDLINE_LINUX_DEFAULT=.*/d' -e'/GRUB_TIMEOUT_STYLE=.*/d' /etc/default/grub
	printf "GRUB_TIMEOUT=0\nGRUB_DISTRIBUTOR=\"Archi3\"\nGRUB_CMDLINE_LINUX_DEFAULT=\"loglevel=3 nomodeset\"\nGRUB_TIMEOUT_STYLE=hidden" >> /etc/default/grub
	grub-mkconfig -o/boot/grub/grub.cfg
fi

