#!/bin/bash

source pkgs

locale-gen
systemctl enable $services

echo 'Enter root passwd'
passwd root
echo 'Enter Username'
read username
echo 'Enter $username passwd'
useradd -m -G wheel $username
passwd $username
if [ $username = 'oran' ]
then
	git config --global user.email "oran.mcnair@gmail.com"
	git config --global user.name "Oran Ellis"
	git config --global credential.helper store
fi

pacman -Sy --noconfirm --needed $pkgs

cp -rf ./dotfiles/.[^.]* $HOME
cp -rf ./scripts/amount /usr/bin

sudo -u oran -H sh -c "cd /home/$username/
mkdir Dev
mkdir Downloads
mkdir Pictures
cd Pictures
mkdir Backgrounds
cd ..
cd Dev
git clone http://aur.archlinux.org/yay
makepkg -sic
cd .. rm -rf yay

yay --save --answerclean All --answerdiff All
yay --save --nocleanmenu --nodiffmenu

yay -S $pkgsyay"
