#!/bin/bash

source pkgs

pacman -Syy
pacman -S --noconfirm $pkgs

locale-gen
systemctl enable $services

echo 'Enter root passwd'
passwd root
echo 'Enter Username'
read username
echo 'Enter $username passwd'
useradd -m -G wheel $username
passwd $username
if [ $username = 'oran' ]
then
	git config --global user.email "oran.mcnair@gmail.com"
	git config --global user.name "Oran Ellis"
	git config --global credential.helper store
fi

cp -rf /dotfiles/.[^.]* $HOME
