#!/bin/bash

dir=$(pwd)
scriptdir=$(dirname $0)
pacstrap $dir base sudo
echo 'KEYMAP=i386/qwerty/uk' >> $dir/etc/vconsole.conf
ln -rsf $dir/usr/share/zoneinfo/Europe/London $dir/etc/localtime
genfstab -U $dir >> $dir/etc/fstab
echo 'oDesktop-i3' >> $dir/etc/hostname
sed -i -e's/#en_US.UTF-8/en_US.UTF-8/g' $dir/etc/locale.gen
sed -i -e's/#en_GB.UTF-8/en_GB.UTF-8/g' $dir/etc/locale.gen
sed -i -e's/# %wheel ALL=(ALL:ALL) NOPASSWD/%wheel ALL=(ALL:ALL) NOPASSWD/g' $dir/etc/sudoers
cp -r "$(dirname $scriptdir)" "$dir"

arch-chroot $dir /bin/bash <<EOT
cd /$(dirname $scriptdir)
./sysinstall
EOT
