#!/bin/bash

locale-gen
systemctl enable iwd dhcpcd
echo 'Enter root passwd'
passwd root
echo 'Enter Username'
read username
echo 'Enter $username passwd'
useradd -m -G wheel $username
passwd $username
pacman -Syy
if [ $username = 'oran' ]
then
	git config --global user.email "oran.mcnair@gmail.com"
	git config --global user.name "Oran Ellis"
	git config --global credential.helper store
fi
rm -f $(pwd)/postinstall
