#!/bin/bash

if [ $# -gt 0 ]
then
    for var in $@
    do
        mkdir -p $HOME/Dev/AUR
        cd $HOME/Dev/AUR
        git clone http://aur.archlinux.org/$var
        cd $var
        git pull
        makepkg -sic --skipinteg --noconfirm --needed
        cd ..
    done
else
    cd $HOME/Dev/AUR
    for var in $(ls)
    do
        cd $HOME/Dev/AUR
        git clone http://aur.archlinux.org/$var
        cd $var
        git pull
        makepkg -sic --skipinteg --noconfirm --needed
        cd ..
    done
fi
